---
- hosts: all
  user: ayqazi
  sudo: True
  tasks:
    - include: tasks/beginning.yml
    - include: tasks/common.yml

- hosts: servers
  user: ayqazi
  sudo: True
  tasks:
    - include: tasks/servers.yml

- hosts: desktops
  user: ayqazi
  sudo: True
  tasks:
    - include: tasks/desktops.yml

- hosts: desktops:&vms
  user: ayqazi
  sudo: True
  tasks:
    - include: tasks/desktops-vms.yml
