---
- name: apt repository $item
  action: command add-apt-repository -y '$item'
  with_items:
    - deb http://archive.canonical.com/ubuntu precise partner
    - ppa:trebelnik-stefina/synergy

- name: apt-get update
  action: apt update_cache=yes

- name: aptitude
  action: apt pkg=aptitude state=latest

- name: aptitude full-upgrade
  action: command /usr/bin/aptitude full-upgrade -y

#- name: remove old kernels
#  action: shell aptitude purge `dpkg -l| awk '$2 ~ /linux-image-[^g]/ {print $2}' | sort# | head -n -1`
