---
- name: apt repository $item
  action: command add-apt-repository -y '$item'
  with_items:
    - ppa:trebelnik-stefina/synergy

- name: apt-get update
  action: apt update_cache=yes

- name: apt-get dist-upgrade
  action: command /usr/bin/apt-get dist-upgrade -y

#- name: remove old kernels
#  action: shell aptitude purge `dpkg -l| awk '$2 ~ /linux-image-[^g]/ {print $2}' | sort# | head -n -1`
