---
- command: apt-add-repository -y '{{ item }}'
  with_items:
    - http://archive.canonical.com/ubuntu partner
    - ppa:webupd8team/java

- apt: update_cache=yes upgrade=dist

- command: debconf-set-selections "{{ dir }}/etc/apt/debconf-selections"

#- name: remove old kernels
#  action: shell aptitude purge `dpkg -l| awk '$2 ~ /linux-image-[^g]/ {print $2}' | sort# | head -n -1`
