---
- apt_key: { url: "https://apt.z.cash/zcash.asc", state: present }

- apt_repository:
    repo: "{{ item }}"
    mode: 644
    state: present
  with_items:
    - "deb http://archive.canonical.com/ubuntu xenial partner"
    - ppa:webupd8team/java
    - ppa:git-core/ppa
    - "deb [arch=amd64] https://apt.z.cash/ jessie main"

- apt: update_cache=yes upgrade=dist

- command: debconf-set-selections "{{ dir }}/etc/apt/debconf-selections"

#- name: remove old kernels
#  action: shell aptitude purge `dpkg -l| awk '$2 ~ /linux-image-[^g]/ {print $2}' | sort# | head -n -1`
