---
- name: purge $item
  action: apt pkg=$item state=removed purge=yes
  with_items:
    - xul-ext-ubufox
    - emacs23
    - emacs23-bin-common
    - emacs23-common
    - emacs23-el
    - emacs23-nox
    - emacs23-lucid
    - auctex

- name: install latest $item
  action: apt pkg=$item state=latest
  with_items:
    - aptitude
    - screen
    - openjdk-7-jdk
    - p7zip
    - ncftp
    - lm-sensors
    - build-essential
    - curl
    - git
    - hddtemp
    - apg
    - pwgen
    - proxychains
    - tshark
    - subversion
    - update-manager
    - tightvncserver
    - fuse-utils
    - links
    - netcat-traditional
    - ntp
    - schedtool
    - pkg-config
    - whois
    - ufw
    - disktype
    - graphicsmagick
    - pbzip2
    - pigz
    - sysstat
    - pv

    - zlib1g-dev
    - libssl-dev
    - libreadline6-dev
    - libxml2-dev
    - libxslt1-dev
    - libmagickwand-dev

    - postgresql-9.1
    - postgresql-client-9.1
    - libpq-dev

    - mysql-client-5.5
    - mysql-server-5.5
    - libmysqlclient-dev

    - emacs24
    - emacs24-el
    - emacs24-common-non-dfsg
