---

- apt: pkg={{ item }} state=latest
  with_items:
    - screen
    - oracle-java9-installer
    - lm-sensors
    - build-essential
    - curl
    - git
    - hddtemp
    - apg
    - pwgen
    - update-manager
    - links
    - netcat-traditional
    - ntp
    - schedtool
    - pkg-config
    - whois
    - ufw
    - pbzip2
    - pv
    - autoconf
    - dstat
    - powertop
    - powertop-1.13
    - iperf

    - zlib1g-dev
    - libssl-dev
    - libreadline6-dev
    - libxml2-dev
    - libxslt1-dev

    - postgresql-9.5
    - postgresql-client-9.5
    - postgresql-contrib-9.5
    - libpq-dev

    - emacs24-el
    - emacs-goodies-el

    - ppa-purge
    - nethogs
    - jq

    - openssh-client
    - openssh-server
    - openssh-blacklist-extra

    - libyaml-dev
    - sqlite3
    - libgdbm-dev
    - libncurses5-dev
    - bison
    - libffi-dev
    - debconf-utils
    - linux-tools-generic
    - libmath-round-perl

- command: update-java-alternatives -s java-9-oracle

- name: add user to groups
  action: user name=ayqazi append=yes groups={{ item }}
  with_items:
    - video
    # - fuse

- lineinfile: dest=/etc/acpi/events/powerbtn state=present regexp=^(action=/etc/acpi/powerbtn\.sh) line='# \1' backrefs=yes

- name: Disable powerkey handling in vtty mode
  ini_file: >
    dest=/etc/systemd/logind.conf
    section=Login
    option=HandlePowerKey
    value=ignore
    backup=yes
  tags: logind

- name: Disable laptop lid close handling in vtty mode
  ini_file: >
    dest=/etc/systemd/logind.conf
    section=Login
    option=HandleLidSwitch
    value=ignore
    backup=yes
  tags: logind

- service: name=systemd-logind state=restarted
  tags: [systemd]

- script: "{{ dir }}/bin/ufw.sh"
  tags: ufw
