---
- name: install latest $item
  action: apt pkg=$item state=latest
  with_items:
    - emacs
    - screen
    - openjdk-7-jdk
    - p7zip
    - ncftp
    - lm-sensors
    - build-essential
    - curl
    - git
    - hddtemp
    - apg
    - pwgen
    - proxychains
    - tshark
    - subversion
    - update-manager
    - tightvncserver
    - fuse-utils
    - links
    - netcat-traditional
    - ntp
    - schedtool
    - pkg-config

    - zlib1g-dev
    - libssl-dev
    - libreadline6-dev
