---

- apt: pkg={{ item }} state=latest
  with_items:
    - aptitude
    - screen
    - openjdk-7-jdk
    - oracle-java8-installer
    - p7zip-full
    - ncftp
    - lm-sensors
    - build-essential
    - curl
    - git
    - hddtemp
    - apg
    - pwgen
    - proxychains
    - tshark
    - subversion
    - update-manager
    - links
    - netcat-traditional
    - ntp
    - schedtool
    - pkg-config
    - whois
    - ufw
    - disktype
    - graphicsmagick
    - pbzip2
    - pigz
    - sysstat
    - pv
    - autoconf
    - dstat
    - powertop
    - powertop-1.13
    - iperf

    - zlib1g-dev
    - libssl-dev
    - libreadline6-dev
    - libxml2-dev
    - libxslt1-dev

    - postgresql-9.3
    - postgresql-client-9.3
    - libpq-dev

    - mysql-client-5.6
    - mysql-server-5.6
    - libmysqlclient-dev

    - emacs24-el
    - emacs-goodies-el

    - ppa-purge
    - nethogs

    - openssh-client
    - openssh-server
    - openssh-blacklist-extra

    - unison
    - reptyr
    - iotop
    - curlftpfs
    - sshfs
    - libyaml-dev
    - sqlite3
    - libgdbm-dev
    - libncurses5-dev
    - bison
    - libffi-dev
    - debconf-utils
    - linux-tools

- command: update-java-alternatives -s java-8-oracle

- name: add user to groups
  action: user name=ayqazi append=yes groups={{ item }}
  with_items:
    - video
    - fuse

- lineinfile: dest=/etc/acpi/events/powerbtn state=present regexp=^(action=/etc/acpi/powerbtn\.sh) line='# \1' backrefs=yes

- copy: dest=/etc/systemd/logind.conf src=../../../etc/systemd/logind.conf
  tags: [systemd]

- service: name=systemd-logind state=restarted
  tags: [systemd]

- script: "{{ dir }}/bin/ufw.sh"
  tags: ufw
