---
- name: install latest $item
  action: apt pkg=$item state=latest
  with_items:
    - screen
    - openjdk-7-jdk
    - p7zip
    - ncftp
    - lm-sensors
    - build-essential
    - curl
    - git
    - hddtemp
    - apg
    - pwgen
    - proxychains
    - tshark
    - subversion
    - update-manager
    - tightvncserver
    - fuse-utils
    - links
    - netcat-traditional
    - ntp
    - schedtool
    - pkg-config
    - whois
    - ufw
    - disktype

    - zlib1g-dev
    - libssl-dev
    - libreadline6-dev
    - libxml2-dev
    - libxslt1-dev
    - libmagickwand-dev

    - postgresql-9.1
    - postgresql-client-9.1
    - libpq-dev

    - mysql-client-5.5
    - mysql-server-5.5
    - libmysqlclient-dev
