---
- name: install $item
  action: apt pkg=$item state=installed
  with_items:
    - chromium-browser
    - gkrellm
    - gkrellm-ibam
    - imwheel
    - pidgin
    - mplayer
    - mrxvt
    - mesa-utils
    - ia32-libs
    - acroread
    - ksshaskpass
    - rdesktop
    - recordmydesktop
    - ubuntu-wallpapers-precise
    - kdewallpapers
    - wireshark
    - x11vnc
    - xtightvncviewer
    - plasma-widget-quickaccess
    - ttf-mscorefonts-installer
    - fonts-droid
    - gimp
    - synergy

    - libgtk2.0-dev
