---
- name: install latest $item
  action: apt pkg=$item state=latest
  with_items:
    - chromium-browser
    - firefox
    - gkrellm
    - gkrellm-ibam
    - imwheel
    - pidgin
    - mplayer
    - mrxvt
    - mesa-utils
    - ia32-libs
    - acroread
    - ksshaskpass
    - rdesktop
    - recordmydesktop
    - ubuntu-wallpapers-precise
    - kdewallpapers
    - wireshark
    - x11vnc
    - xtightvncviewer
    - plasma-widget-quickaccess
    - ttf-mscorefonts-installer
    - fonts-droid
    - gimp
    - synergy
    - adobe-flashplugin
    - emacs23
    - emacs-goodies-el

    - libgtk2.0-dev

- name: purge $item
  action: apt pkg=$item state=removed purge=yes
  with_items:
    - xul-ext-ubufox
