---
- name: "Remove unwanted packages"
  apt: pkg={{ item }} state=removed purge=yes
  with_items:
    - kubuntu-firefox-installer

- apt: pkg={{ item }} state=latest
  with_items:
    - kubuntu-restricted-addons
    - chromium-browser
    - chromium-codecs-ffmpeg-extra
    - firefox
    - firefox-locale-en
    - gkrellm
    - gkrellm-ibam
    - imwheel
    - pidgin
    - mplayer
    - mrxvt
    - mesa-utils
    - ksshaskpass
    - rdesktop
    - recordmydesktop
    - ubuntu-wallpapers-precise
    - kdewallpapers
    - wireshark
    - x11vnc
    - xtightvncviewer
    - fonts-droid-fallback
    - gimp
    - audacity
    - gparted
    - skype
    - ttf-mscorefonts-installer
    - emacs24

    - libgtk2.0-dev

    - powermanagement-interface

    - libgtk2.0-0:i386 # required by acroread binaries

- name: purge (after others) {{ item }}
  action: apt pkg={{ item }} state=removed purge=yes
  with_items:
    - xul-ext-ubufox
