---
- name: install latest $item
  action: apt pkg=$item state=latest
  with_items:
    - kubuntu-restricted-addons
    - chromium-browser
    - firefox
    - gkrellm
    - gkrellm-ibam
    - imwheel
    - pidgin
    - mplayer
    - mrxvt
    - mesa-utils
    - ia32-libs
    - acroread
    - ksshaskpass
    - rdesktop
    - recordmydesktop
    - ubuntu-wallpapers-precise
    - kdewallpapers
    - wireshark
    - x11vnc
    - xtightvncviewer
    - plasma-widget-quickaccess
    - fonts-droid
    - gimp
    - synergy
    - adobe-flashplugin
    - audacity
    - gparted

    - libgtk2.0-dev
